[pytest]
addopts =
    -v
    -s

;    --headed
;    --browser=chromium
;    --video=retain-on-failure;
;    --screenshot=only-on-failure
;    --tracing=retain-on-failure
    --html=myreport.html --self-contained-html --capture=tee-sys
; for html report you have install plugin pytest-html
;    --alluredir=reports/allure-results

